version: "2.4"

services:
  frontend:
    build: 
      context: ./frontend
      target: development
    entrypoint: npm start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    environment:  
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true